// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoutingSheetsNew.Data;

#nullable disable

namespace RoutingSheetsNew.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220180228_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoutingSheetsNew.Models.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GuildId")
                        .HasColumnType("int")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("OperationTypeId")
                        .HasColumnType("int")
                        .HasColumnName("operation_type_id");

                    b.Property<int?>("PerformerId")
                        .HasColumnType("int")
                        .HasColumnName("performer_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RoutingSheetId")
                        .HasColumnType("int")
                        .HasColumnName("routing_sheet_id");

                    b.Property<int>("SeqNumber")
                        .HasColumnType("int")
                        .HasColumnName("seq_number");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<decimal?>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("OperationTypeId");

                    b.HasIndex("PerformerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("RoutingSheetId", "SeqNumber");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.OperationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OperationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PENDING",
                            Name = "Ожидает"
                        },
                        new
                        {
                            Id = 2,
                            Code = "IN_PROGRESS",
                            Name = "В работе"
                        },
                        new
                        {
                            Id = 3,
                            Code = "COMPLETED",
                            Name = "Завершена"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CANCELLED",
                            Name = "Отменена"
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.OperationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("OperationTypes");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Performer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("full_name");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.PlanPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("position_code");

                    b.Property<int>("ProductItemId")
                        .HasColumnType("int")
                        .HasColumnName("product_item_id");

                    b.Property<int>("QuantityPlanned")
                        .HasColumnType("int")
                        .HasColumnName("quantity_planned");

                    b.HasKey("Id");

                    b.HasIndex("PositionCode");

                    b.HasIndex("ProductItemId");

                    b.ToTable("PlanPositions");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.ProductItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("QuantityPlanned")
                        .HasColumnType("int")
                        .HasColumnName("quantity_planned");

                    b.HasKey("Id");

                    b.ToTable("ProductItems");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.RoutingSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PlanPositionId")
                        .HasColumnType("int")
                        .HasColumnName("plan_position_id");

                    b.Property<int?>("ProductItemId")
                        .HasColumnType("int")
                        .HasColumnName("product_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("PlanPositionId");

                    b.HasIndex("ProductItemId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UnitId");

                    b.ToTable("RoutingSheets");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.RoutingSheetStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("RoutingSheetStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DRAFT",
                            Name = "Черновик"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ACTIVE",
                            Name = "Активен"
                        },
                        new
                        {
                            Id = 3,
                            Code = "COMPLETED",
                            Name = "Завершен"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CANCELLED",
                            Name = "Отменен"
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Operation", b =>
                {
                    b.HasOne("RoutingSheetsNew.Models.Guild", "Guild")
                        .WithMany("Operations")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoutingSheetsNew.Models.OperationType", "OperationType")
                        .WithMany("Operations")
                        .HasForeignKey("OperationTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoutingSheetsNew.Models.Performer", "Performer")
                        .WithMany("Operations")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoutingSheetsNew.Models.RoutingSheet", "RoutingSheet")
                        .WithMany("Operations")
                        .HasForeignKey("RoutingSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoutingSheetsNew.Models.OperationStatus", "Status")
                        .WithMany("Operations")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Guild");

                    b.Navigation("OperationType");

                    b.Navigation("Performer");

                    b.Navigation("RoutingSheet");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.PlanPosition", b =>
                {
                    b.HasOne("RoutingSheetsNew.Models.ProductItem", "ProductItem")
                        .WithMany("PlanPositions")
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductItem");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.RoutingSheet", b =>
                {
                    b.HasOne("RoutingSheetsNew.Models.PlanPosition", "PlanPosition")
                        .WithMany("RoutingSheets")
                        .HasForeignKey("PlanPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoutingSheetsNew.Models.ProductItem", "ProductItem")
                        .WithMany("RoutingSheets")
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoutingSheetsNew.Models.RoutingSheetStatus", "Status")
                        .WithMany("RoutingSheets")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoutingSheetsNew.Models.Unit", "Unit")
                        .WithMany("RoutingSheets")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PlanPosition");

                    b.Navigation("ProductItem");

                    b.Navigation("Status");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Guild", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.OperationStatus", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.OperationType", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Performer", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.PlanPosition", b =>
                {
                    b.Navigation("RoutingSheets");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.ProductItem", b =>
                {
                    b.Navigation("PlanPositions");

                    b.Navigation("RoutingSheets");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.RoutingSheet", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.RoutingSheetStatus", b =>
                {
                    b.Navigation("RoutingSheets");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Unit", b =>
                {
                    b.Navigation("RoutingSheets");
                });
#pragma warning restore 612, 618
        }
    }
}
