// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoutingSheetsNew.Data;

#nullable disable

namespace RoutingSheetsNew.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RoutingSheetsNew.Models.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Guilds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Сборочный цех №1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Механический цех №2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Сварочный цех №3"
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuildId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperationTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("operation_type_id");

                    b.Property<int?>("PerformerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("performer_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoutingSheetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("routing_sheet_id");

                    b.Property<int>("SeqNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seq_number");

                    b.Property<int?>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_id");

                    b.Property<decimal?>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("OperationTypeId");

                    b.HasIndex("PerformerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("RoutingSheetId", "SeqNumber");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.OperationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OperationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PENDING",
                            Name = "Ожидает"
                        },
                        new
                        {
                            Id = 2,
                            Code = "IN_PROGRESS",
                            Name = "В работе"
                        },
                        new
                        {
                            Id = 3,
                            Code = "COMPLETED",
                            Name = "Завершена"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CANCELLED",
                            Name = "Отменена"
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.OperationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OperationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Сборка"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Сварка"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Токарная обработка"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Фрезерная обработка"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Контроль качества"
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Основной корпус изделия",
                            Name = "Корпус"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Крышка корпуса",
                            Name = "Крышка"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Приводной вал",
                            Name = "Вал"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ведущая шестерня",
                            Name = "Шестерня"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Опорный подшипник",
                            Name = "Подшипник"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Крепёжный болт М6",
                            Name = "Болт М6"
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.PartOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuildId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperationTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("operation_type_id");

                    b.Property<int>("PartId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("part_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeqNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seq_number");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("OperationTypeId");

                    b.HasIndex("PartId", "SeqNumber");

                    b.ToTable("PartOperations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ПО-001",
                            GuildId = 2,
                            Name = "Фрезеровка корпуса",
                            OperationTypeId = 4,
                            PartId = 1,
                            Price = 300.00m,
                            SeqNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "ПО-002",
                            GuildId = 2,
                            Name = "Контроль корпуса",
                            OperationTypeId = 5,
                            PartId = 1,
                            Price = 50.00m,
                            SeqNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "ПО-003",
                            GuildId = 1,
                            Name = "Штамповка заготовки крышки",
                            OperationTypeId = 1,
                            PartId = 2,
                            Price = 30.00m,
                            SeqNumber = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "ПО-004",
                            GuildId = 2,
                            Name = "Шлифовка крышки",
                            OperationTypeId = 4,
                            PartId = 2,
                            Price = 20.00m,
                            SeqNumber = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "ПО-005",
                            GuildId = 2,
                            Name = "Токарная обработка вала",
                            OperationTypeId = 3,
                            PartId = 3,
                            Price = 250.00m,
                            SeqNumber = 1
                        },
                        new
                        {
                            Id = 6,
                            Code = "ПО-006",
                            GuildId = 2,
                            Name = "Фрезеровка шестерни",
                            OperationTypeId = 4,
                            PartId = 4,
                            Price = 180.00m,
                            SeqNumber = 1
                        },
                        new
                        {
                            Id = 7,
                            Code = "ПО-007",
                            GuildId = 3,
                            Name = "Термообработка шестерни",
                            OperationTypeId = 2,
                            PartId = 4,
                            Price = 100.00m,
                            SeqNumber = 2
                        },
                        new
                        {
                            Id = 8,
                            Code = "ПО-008",
                            GuildId = 1,
                            Name = "Контроль подшипника",
                            OperationTypeId = 5,
                            PartId = 5,
                            Price = 20.00m,
                            SeqNumber = 1
                        },
                        new
                        {
                            Id = 9,
                            Code = "ПО-009",
                            GuildId = 2,
                            Name = "Токарная обработка болта",
                            OperationTypeId = 3,
                            PartId = 6,
                            Price = 10.00m,
                            SeqNumber = 1
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Performer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Performers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Иванов Иван Иванович",
                            Role = "Слесарь-сборщик"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Петров Петр Петрович",
                            Role = "Сварщик"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Сидоров Сидор Сидорович",
                            Role = "Токарь"
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.PlanPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("date")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("document_number");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("plan_month");

                    b.Property<int>("PlanYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("plan_year");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("position_code");

                    b.Property<int>("ProductItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_item_id");

                    b.Property<int>("QuantityPlanned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity_planned");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_id");

                    b.HasKey("Id");

                    b.HasIndex("PositionCode");

                    b.HasIndex("ProductItemId");

                    b.HasIndex("StatusId");

                    b.HasIndex("GuildId", "PlanYear", "PlanMonth");

                    b.ToTable("PlanPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "ПП-2026-001",
                            GuildId = 1,
                            Name = "Производство корпусов, январь",
                            PlanMonth = 1,
                            PlanYear = 2026,
                            PositionCode = "ПП-2026-001",
                            ProductItemId = 1,
                            QuantityPlanned = 25,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            DocumentDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "ПП-2026-002",
                            GuildId = 2,
                            Name = "Производство валов, январь",
                            PlanMonth = 1,
                            PlanYear = 2026,
                            PositionCode = "ПП-2026-002",
                            ProductItemId = 2,
                            QuantityPlanned = 15,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            DocumentDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "ПП-2026-003",
                            GuildId = 2,
                            Name = "Производство шестерен, январь",
                            PlanMonth = 1,
                            PlanYear = 2026,
                            PositionCode = "ПП-2026-003",
                            ProductItemId = 3,
                            QuantityPlanned = 50,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 4,
                            DocumentDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "ПП-2026-004",
                            GuildId = 1,
                            Name = "Производство корпусов, февраль",
                            PlanMonth = 2,
                            PlanYear = 2026,
                            PositionCode = "ПП-2026-004",
                            ProductItemId = 1,
                            QuantityPlanned = 30,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 5,
                            DocumentDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "ПП-2026-005",
                            GuildId = 2,
                            Name = "Производство валов, февраль",
                            PlanMonth = 2,
                            PlanYear = 2026,
                            PositionCode = "ПП-2026-005",
                            ProductItemId = 2,
                            QuantityPlanned = 20,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 6,
                            DocumentDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "ПП-2026-006",
                            GuildId = 2,
                            Name = "Производство шестерен, февраль",
                            PlanMonth = 2,
                            PlanYear = 2026,
                            PositionCode = "ПП-2026-006",
                            ProductItemId = 3,
                            QuantityPlanned = 40,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 7,
                            DocumentDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "ПП-2026-007",
                            GuildId = 1,
                            Name = "Производство корпусов (доп.), февраль",
                            PlanMonth = 2,
                            PlanYear = 2026,
                            PositionCode = "ПП-2026-007",
                            ProductItemId = 1,
                            QuantityPlanned = 10,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.PlanStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlanStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "OPEN",
                            Name = "Открыт"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CLOSED",
                            Name = "Закрыт"
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.ProductItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Корпус для промышленного редуктора РМ-500",
                            Name = "Корпус редуктора"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Приводной вал для станка",
                            Name = "Вал приводной"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ведущая шестерня z=24",
                            Name = "Шестерня ведущая"
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.ProductPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("part_id");

                    b.Property<int>("ProductItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("ProductItemId", "PartId")
                        .IsUnique();

                    b.ToTable("ProductParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PartId = 1,
                            ProductItemId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            PartId = 2,
                            ProductItemId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            PartId = 6,
                            ProductItemId = 1,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 4,
                            PartId = 3,
                            ProductItemId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            PartId = 5,
                            ProductItemId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 6,
                            PartId = 4,
                            ProductItemId = 3,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.RoutingSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("part_id");

                    b.Property<int?>("PlanPositionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("plan_position_id");

                    b.Property<int?>("ProductItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_id");

                    b.Property<int?>("UnitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("PartId");

                    b.HasIndex("PlanPositionId");

                    b.HasIndex("PlanPositionId", "PartId")
                        .IsUnique();

                    b.HasIndex("ProductItemId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UnitId");

                    b.ToTable("RoutingSheets");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.RoutingSheetStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoutingSheetStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DRAFT",
                            Name = "Черновик"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ACTIVE",
                            Name = "Активен"
                        },
                        new
                        {
                            Id = 3,
                            Code = "COMPLETED",
                            Name = "Завершен"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CANCELLED",
                            Name = "Отменен"
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "шт."
                        },
                        new
                        {
                            Id = 2,
                            Name = "кг"
                        },
                        new
                        {
                            Id = 3,
                            Name = "м"
                        });
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuildId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("guild_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Operation", b =>
                {
                    b.HasOne("RoutingSheetsNew.Models.Guild", "Guild")
                        .WithMany("Operations")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoutingSheetsNew.Models.OperationType", "OperationType")
                        .WithMany("Operations")
                        .HasForeignKey("OperationTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoutingSheetsNew.Models.Performer", "Performer")
                        .WithMany("Operations")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoutingSheetsNew.Models.RoutingSheet", "RoutingSheet")
                        .WithMany("Operations")
                        .HasForeignKey("RoutingSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoutingSheetsNew.Models.OperationStatus", "Status")
                        .WithMany("Operations")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Guild");

                    b.Navigation("OperationType");

                    b.Navigation("Performer");

                    b.Navigation("RoutingSheet");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.PartOperation", b =>
                {
                    b.HasOne("RoutingSheetsNew.Models.Guild", "Guild")
                        .WithMany("PartOperations")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoutingSheetsNew.Models.OperationType", "OperationType")
                        .WithMany("PartOperations")
                        .HasForeignKey("OperationTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoutingSheetsNew.Models.Part", "Part")
                        .WithMany("PartOperations")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("OperationType");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.PlanPosition", b =>
                {
                    b.HasOne("RoutingSheetsNew.Models.Guild", "Guild")
                        .WithMany("PlanPositions")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoutingSheetsNew.Models.ProductItem", "ProductItem")
                        .WithMany("PlanPositions")
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoutingSheetsNew.Models.PlanStatus", "Status")
                        .WithMany("PlanPositions")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("ProductItem");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.ProductPart", b =>
                {
                    b.HasOne("RoutingSheetsNew.Models.Part", "Part")
                        .WithMany("ProductParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoutingSheetsNew.Models.ProductItem", "ProductItem")
                        .WithMany("ProductParts")
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("ProductItem");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.RoutingSheet", b =>
                {
                    b.HasOne("RoutingSheetsNew.Models.Part", "Part")
                        .WithMany("RoutingSheets")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoutingSheetsNew.Models.PlanPosition", "PlanPosition")
                        .WithMany("RoutingSheets")
                        .HasForeignKey("PlanPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoutingSheetsNew.Models.ProductItem", "ProductItem")
                        .WithMany("RoutingSheets")
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoutingSheetsNew.Models.RoutingSheetStatus", "Status")
                        .WithMany("RoutingSheets")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoutingSheetsNew.Models.Unit", "Unit")
                        .WithMany("RoutingSheets")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PlanPosition");

                    b.Navigation("Part");

                    b.Navigation("ProductItem");

                    b.Navigation("Status");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.User", b =>
                {
                    b.HasOne("RoutingSheetsNew.Models.Guild", "Guild")
                        .WithMany("Users")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Guild", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("PartOperations");

                    b.Navigation("PlanPositions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.OperationStatus", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.OperationType", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("PartOperations");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Part", b =>
                {
                    b.Navigation("PartOperations");

                    b.Navigation("ProductParts");

                    b.Navigation("RoutingSheets");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Performer", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.PlanPosition", b =>
                {
                    b.Navigation("RoutingSheets");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.PlanStatus", b =>
                {
                    b.Navigation("PlanPositions");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.ProductItem", b =>
                {
                    b.Navigation("PlanPositions");

                    b.Navigation("ProductParts");

                    b.Navigation("RoutingSheets");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.RoutingSheet", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.RoutingSheetStatus", b =>
                {
                    b.Navigation("RoutingSheets");
                });

            modelBuilder.Entity("RoutingSheetsNew.Models.Unit", b =>
                {
                    b.Navigation("RoutingSheets");
                });
#pragma warning restore 612, 618
        }
    }
}
